swagger: "2.0"
info:
  version: "0.0.1"
  title: RJ Insurance Co. Facade
# during dev, should point to your local machine
host: 130.211.118.83:8080
# basePath prefixes all resource paths 
basePath: /v1
#
tags:
  -
    name: "dashboard"
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /getdashboarddata:
    # binds a127 app logic to a route
    x-swagger-router-controller: ctl_dashboard
    get:
      tags:
        - "dashboard"   
      description: Returns consolidated dashboard data to the caller
      # used as the method name of the controller
      operationId: getdashboarddata
      parameters:
        - name: clientid
          in: query
          description: The id of the client whose information needs to be fetched
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DashboardResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /ping:
    # binds a127 app logic to a route
    x-swagger-router-controller: ctl_ping
    get:
      tags:
        - "health"    
      description: Returns the health status of this service
      # used as the method name of the controller
      operationId: ping
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PingResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  Product: 
      properties: 
        product_id_num: 
          type: "string"
        product_num: 
          type: "string"
        product_type_cde: 
          type: "string"
        role_type_txt: 
          type: "string"
        payment_amount: 
          type: "string"
        payment_freq: 
          type: "string"
        owner_type_cde: 
          type: "string"
        plan_txt: 
          type: "string"
        benefit_amt: 
          type: "string"
        total_value: 
          type: "string"
        dividend_amt: 
          type: "string"
        loan_amt: 
          type: "string"
      xml: 
        name: "Product"
  Client: 
      properties: 
        client_id: 
          type: "string"
        client_type_cde: 
          type: "string"
        taxpayer_id: 
          type: "string"
        full_name: 
          type: "string"
        email: 
          type: "string"
        birth_dte: 
          type: "string"
        products:
          type: "array"
          items:
            $ref: "#/definitions/Product"
      xml: 
        name: "Client"         
  DashboardResponse:
      properties:
        client:
          type: "array"
          items:
            $ref: "#/definitions/Client"
      xml:
        name: "Dashboard" 
  PingResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
